export type ColorStatus = 'tokenized' | 'unresolved'

export type ColorCategory =
  | 'core'
  | 'status'
  | 'form'
  | 'chart'
  | 'client-palette'
  | 'progress'
  | 'pdf'
  | 'brand'

export type ColorEntry = {
  id: string
  value: string // light-mode value (for tokenized colors that differ between modes)
  token: string | null // CSS variable name, e.g. "--primary"
  tailwindClass: string | null // Tailwind class name, e.g. "primary"
  category: ColorCategory
  label: string
  usedIn: string[] // filenames for brevity (best-effort snapshot)
  status: ColorStatus
}

export const colorRegistry: ColorEntry[] = [
  // ─── Core ──────────────────────────────────────────────────────────────
  {
    id: 'background',
    value: 'oklch(0.97 0.008 70)',
    token: '--background',
    tailwindClass: 'background',
    category: 'core',
    label: 'Background',
    usedIn: ['layouts', 'pages'],
    status: 'tokenized',
  },
  {
    id: 'foreground',
    value: 'oklch(0.18 0.005 70)',
    token: '--foreground',
    tailwindClass: 'foreground',
    category: 'core',
    label: 'Foreground',
    usedIn: ['layouts', 'pages'],
    status: 'tokenized',
  },
  {
    id: 'card',
    value: 'oklch(0.97 0.008 70)',
    token: '--card',
    tailwindClass: 'card',
    category: 'core',
    label: 'Card',
    usedIn: ['Card component'],
    status: 'tokenized',
  },
  {
    id: 'card-foreground',
    value: 'oklch(0.18 0.005 70)',
    token: '--card-foreground',
    tailwindClass: 'card-foreground',
    category: 'core',
    label: 'Card Foreground',
    usedIn: ['Card component'],
    status: 'tokenized',
  },
  {
    id: 'popover',
    value: 'oklch(0.98 0.006 70)',
    token: '--popover',
    tailwindClass: 'popover',
    category: 'core',
    label: 'Popover',
    usedIn: ['Popover', 'DropdownMenu', 'command.tsx'],
    status: 'tokenized',
  },
  {
    id: 'popover-foreground',
    value: 'oklch(0.18 0.005 70)',
    token: '--popover-foreground',
    tailwindClass: 'popover-foreground',
    category: 'core',
    label: 'Popover Foreground',
    usedIn: ['Popover', 'DropdownMenu'],
    status: 'tokenized',
  },
  {
    id: 'primary',
    value: 'oklch(0.36 0.05 163)',
    token: '--primary',
    tailwindClass: 'primary',
    category: 'core',
    label: 'Primary',
    usedIn: ['buttons', 'links', 'sidebar'],
    status: 'tokenized',
  },
  {
    id: 'primary-foreground',
    value: 'oklch(0.98 0.006 70)',
    token: '--primary-foreground',
    tailwindClass: 'primary-foreground',
    category: 'core',
    label: 'Primary Foreground',
    usedIn: ['buttons'],
    status: 'tokenized',
  },
  {
    id: 'secondary',
    value: 'oklch(0.84 0.16 90)',
    token: '--secondary',
    tailwindClass: 'secondary',
    category: 'core',
    label: 'Secondary',
    usedIn: ['secondary buttons', 'accents'],
    status: 'tokenized',
  },
  {
    id: 'secondary-foreground',
    value: 'oklch(0.25 0.02 70)',
    token: '--secondary-foreground',
    tailwindClass: 'secondary-foreground',
    category: 'core',
    label: 'Secondary Foreground',
    usedIn: ['secondary buttons'],
    status: 'tokenized',
  },
  {
    id: 'accent',
    value: 'oklch(0.68 0.09 280)',
    token: '--accent',
    tailwindClass: 'accent',
    category: 'core',
    label: 'Accent',
    usedIn: ['accent highlights'],
    status: 'tokenized',
  },
  {
    id: 'accent-foreground',
    value: 'oklch(0.98 0.006 70)',
    token: '--accent-foreground',
    tailwindClass: 'accent-foreground',
    category: 'core',
    label: 'Accent Foreground',
    usedIn: ['accent buttons'],
    status: 'tokenized',
  },
  {
    id: 'muted',
    value: '#E9E2DB',
    token: '--muted',
    tailwindClass: 'muted',
    category: 'core',
    label: 'Muted',
    usedIn: ['muted backgrounds', 'disabled states'],
    status: 'tokenized',
  },
  {
    id: 'muted-foreground',
    value: 'oklch(0.55 0.02 70)',
    token: '--muted-foreground',
    tailwindClass: 'muted-foreground',
    category: 'core',
    label: 'Muted Foreground',
    usedIn: ['placeholder text', 'hints'],
    status: 'tokenized',
  },
  {
    id: 'destructive',
    value: 'oklch(0.58 0.22 27)',
    token: '--destructive',
    tailwindClass: 'destructive',
    category: 'core',
    label: 'Destructive',
    usedIn: ['delete buttons', 'error states'],
    status: 'tokenized',
  },
  {
    id: 'border',
    value: 'oklch(0.92 0.012 70)',
    token: '--border',
    tailwindClass: 'border',
    category: 'core',
    label: 'Border',
    usedIn: ['input borders', 'dividers'],
    status: 'tokenized',
  },
  {
    id: 'input',
    value: 'oklch(0.92 0.012 70)',
    token: '--input',
    tailwindClass: 'input',
    category: 'core',
    label: 'Input',
    usedIn: ['form inputs'],
    status: 'tokenized',
  },
  {
    id: 'ring',
    value: 'oklch(0.58 0.05 163)',
    token: '--ring',
    tailwindClass: 'ring',
    category: 'core',
    label: 'Ring',
    usedIn: ['focus rings'],
    status: 'tokenized',
  },
  {
    id: 'sidebar',
    value: '#F0EAE4',
    token: '--sidebar',
    tailwindClass: 'sidebar',
    category: 'core',
    label: 'Sidebar',
    usedIn: ['sidebar background'],
    status: 'tokenized',
  },
  {
    id: 'sidebar-foreground',
    value: 'oklch(0.18 0.005 70)',
    token: '--sidebar-foreground',
    tailwindClass: 'sidebar-foreground',
    category: 'core',
    label: 'Sidebar Foreground',
    usedIn: ['sidebar text'],
    status: 'tokenized',
  },
  {
    id: 'sidebar-primary',
    value: 'oklch(0.36 0.05 163)',
    token: '--sidebar-primary',
    tailwindClass: 'sidebar-primary',
    category: 'core',
    label: 'Sidebar Primary',
    usedIn: ['sidebar active item'],
    status: 'tokenized',
  },
  {
    id: 'sidebar-primary-foreground',
    value: 'oklch(0.98 0.006 70)',
    token: '--sidebar-primary-foreground',
    tailwindClass: 'sidebar-primary-foreground',
    category: 'core',
    label: 'Sidebar Primary FG',
    usedIn: ['sidebar active text'],
    status: 'tokenized',
  },
  {
    id: 'sidebar-accent',
    value: '#E5DED7',
    token: '--sidebar-accent',
    tailwindClass: 'sidebar-accent',
    category: 'core',
    label: 'Sidebar Accent',
    usedIn: ['sidebar hover'],
    status: 'tokenized',
  },
  {
    id: 'sidebar-accent-foreground',
    value: 'oklch(0.18 0.005 70)',
    token: '--sidebar-accent-foreground',
    tailwindClass: 'sidebar-accent-foreground',
    category: 'core',
    label: 'Sidebar Accent FG',
    usedIn: ['sidebar hover text'],
    status: 'tokenized',
  },
  {
    id: 'sidebar-border',
    value: 'oklch(0.83 0.017 70)',
    token: '--sidebar-border',
    tailwindClass: 'sidebar-border',
    category: 'core',
    label: 'Sidebar Border',
    usedIn: ['sidebar dividers'],
    status: 'tokenized',
  },
  {
    id: 'sidebar-ring',
    value: 'oklch(0.58 0.05 163)',
    token: '--sidebar-ring',
    tailwindClass: 'sidebar-ring',
    category: 'core',
    label: 'Sidebar Ring',
    usedIn: ['sidebar focus ring'],
    status: 'tokenized',
  },

  // ─── Status ────────────────────────────────────────────────────────────
  {
    id: 'status-paid',
    value: '#45825d',
    token: '--status-paid',
    tailwindClass: 'status-paid',
    category: 'status',
    label: 'Paid',
    usedIn: ['ProjectList.tsx', 'TimeEntryList.tsx', 'InvoicingPage.tsx', 'ReportsPage.tsx'],
    status: 'tokenized',
  },
  {
    id: 'status-invoiced',
    value: '#fddd74',
    token: '--status-invoiced',
    tailwindClass: 'status-invoiced',
    category: 'status',
    label: 'Invoiced',
    usedIn: ['InvoicingPage.tsx', 'ReportsPage.tsx'],
    status: 'tokenized',
  },
  {
    id: 'status-not-paid',
    value: '#e1d4c0',
    token: '--status-not-paid',
    tailwindClass: 'status-not-paid',
    category: 'status',
    label: 'Not Paid',
    usedIn: ['InvoicingPage.tsx', 'ReportsPage.tsx'],
    status: 'tokenized',
  },

  // ─── Form (unresolved) ────────────────────────────────────────────────
  {
    id: 'form-border',
    value: '#eae3dc',
    token: null,
    tailwindClass: null,
    category: 'form',
    label: 'Form Border',
    usedIn: ['dialog.tsx', 'input.tsx', 'textarea.tsx', 'ClientForm.tsx', 'ProjectForm.tsx'],
    status: 'unresolved',
  },
  {
    id: 'form-dialog-bg',
    value: '#f9f4ef',
    token: null,
    tailwindClass: null,
    category: 'form',
    label: 'Dialog Background',
    usedIn: ['dialog.tsx', 'ClientForm.tsx', 'ProjectForm.tsx'],
    status: 'unresolved',
  },
  {
    id: 'form-dialog-footer',
    value: '#f4efea',
    token: null,
    tailwindClass: null,
    category: 'form',
    label: 'Dialog Footer',
    usedIn: ['dialog.tsx'],
    status: 'unresolved',
  },
  {
    id: 'form-input-bg',
    value: '#f9f5f0',
    token: null,
    tailwindClass: null,
    category: 'form',
    label: 'Input Background',
    usedIn: ['input.tsx', 'textarea.tsx'],
    status: 'unresolved',
  },
  {
    id: 'form-group-header-bg',
    value: '#f0eae4',
    token: null,
    tailwindClass: null,
    category: 'form',
    label: 'Group Header BG',
    usedIn: ['ClientForm.tsx', 'ProjectForm.tsx'],
    status: 'unresolved',
  },

  // ─── Chart (tokenized) ────────────────────────────────────────────────
  {
    id: 'chart-1',
    value: 'oklch(0.36 0.05 163)',
    token: '--chart-1',
    tailwindClass: 'chart-1',
    category: 'chart',
    label: 'Chart 1 (Green)',
    usedIn: ['ReportsPage.tsx'],
    status: 'tokenized',
  },
  {
    id: 'chart-2',
    value: 'oklch(0.84 0.16 90)',
    token: '--chart-2',
    tailwindClass: 'chart-2',
    category: 'chart',
    label: 'Chart 2 (Yellow)',
    usedIn: ['ReportsPage.tsx'],
    status: 'tokenized',
  },
  {
    id: 'chart-3',
    value: 'oklch(0.68 0.09 280)',
    token: '--chart-3',
    tailwindClass: 'chart-3',
    category: 'chart',
    label: 'Chart 3 (Lilac)',
    usedIn: ['ReportsPage.tsx'],
    status: 'tokenized',
  },
  {
    id: 'chart-4',
    value: 'oklch(0.50 0.08 163)',
    token: '--chart-4',
    tailwindClass: 'chart-4',
    category: 'chart',
    label: 'Chart 4 (Muted Green)',
    usedIn: ['ReportsPage.tsx'],
    status: 'tokenized',
  },
  {
    id: 'chart-5',
    value: 'oklch(0.75 0.12 90)',
    token: '--chart-5',
    tailwindClass: 'chart-5',
    category: 'chart',
    label: 'Chart 5 (Bright Yellow)',
    usedIn: ['ReportsPage.tsx'],
    status: 'tokenized',
  },

  // ─── Chart (unresolved — hardcoded in ReportsPage) ─────────────────────
  {
    id: 'chart-report-indigo',
    value: '#6366f1',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Indigo',
    usedIn: ['ReportsPage.tsx', 'OnboardingWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-amber',
    value: '#f59e0b',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Amber',
    usedIn: ['ReportsPage.tsx', 'ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-emerald',
    value: '#10b981',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Emerald',
    usedIn: ['ReportsPage.tsx', 'ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-red',
    value: '#ef4444',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Red',
    usedIn: ['ReportsPage.tsx', 'ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-violet',
    value: '#8b5cf6',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Violet',
    usedIn: ['ReportsPage.tsx', 'ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-pink',
    value: '#ec4899',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Pink',
    usedIn: ['ReportsPage.tsx', 'ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-teal',
    value: '#14b8a6',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Teal',
    usedIn: ['ReportsPage.tsx', 'ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-orange',
    value: '#f97316',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Orange',
    usedIn: ['ReportsPage.tsx', 'ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-blue',
    value: '#3b82f6',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Blue',
    usedIn: ['ReportsPage.tsx', 'ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-lime',
    value: '#84cc16',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Lime',
    usedIn: ['ReportsPage.tsx'],
    status: 'unresolved',
  },
  {
    id: 'chart-report-fallback',
    value: '#c4b5a0',
    token: null,
    tailwindClass: null,
    category: 'chart',
    label: 'Report Fallback (Tan)',
    usedIn: ['ReportsPage.tsx'],
    status: 'unresolved',
  },

  // ─── Client Palette ────────────────────────────────────────────────────
  {
    id: 'client-red',
    value: '#ed3838',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Red',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-orange',
    value: '#f97316',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Orange',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-amber',
    value: '#f6b03a',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Amber',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-emerald',
    value: '#96c46e',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Emerald',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-teal',
    value: '#14b8b8',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Teal',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-sky',
    value: '#0ea5e9',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Sky',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-blue',
    value: '#5b8bfc',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Blue',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-indigo',
    value: '#7663f7',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Indigo',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-violet',
    value: '#b35cf6',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Violet',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-pink',
    value: '#f155ab',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Pink',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-slate',
    value: '#6789b9',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Slate (Default)',
    usedIn: ['color-swatch-picker.tsx', 'TimeEntryRow.tsx', 'ProjectCombobox.tsx', 'ProjectList.tsx', 'InvoicingPage.tsx', 'TimeEntriesPage.tsx', 'ReportsPage.tsx'],
    status: 'unresolved',
  },
  {
    id: 'client-black',
    value: '#000000',
    token: null,
    tailwindClass: null,
    category: 'client-palette',
    label: 'Black',
    usedIn: ['color-swatch-picker.tsx'],
    status: 'unresolved',
  },

  // ─── Progress ──────────────────────────────────────────────────────────
  {
    id: 'progress-empty',
    value: '#c8c8c8',
    token: null,
    tailwindClass: null,
    category: 'progress',
    label: 'Empty Bar',
    usedIn: ['ProjectList.tsx', 'TimeEntryList.tsx'],
    status: 'unresolved',
  },
  {
    id: 'progress-overtime',
    value: '#C75042',
    token: null,
    tailwindClass: null,
    category: 'progress',
    label: 'Overtime (Red)',
    usedIn: ['ProjectList.tsx', 'TimeEntryList.tsx'],
    status: 'unresolved',
  },

  // ─── PDF ───────────────────────────────────────────────────────────────
  {
    id: 'pdf-text',
    value: '#666666',
    token: null,
    tailwindClass: null,
    category: 'pdf',
    label: 'PDF Text',
    usedIn: ['pdf-report.tsx'],
    status: 'unresolved',
  },
  {
    id: 'pdf-text-light',
    value: '#888888',
    token: null,
    tailwindClass: null,
    category: 'pdf',
    label: 'PDF Light Text',
    usedIn: ['pdf-report.tsx'],
    status: 'unresolved',
  },
  {
    id: 'pdf-text-faint',
    value: '#999999',
    token: null,
    tailwindClass: null,
    category: 'pdf',
    label: 'PDF Faint Text',
    usedIn: ['pdf-report.tsx'],
    status: 'unresolved',
  },
  {
    id: 'pdf-bg',
    value: '#f5f5f5',
    token: null,
    tailwindClass: null,
    category: 'pdf',
    label: 'PDF Background',
    usedIn: ['pdf-report.tsx'],
    status: 'unresolved',
  },
  {
    id: 'pdf-border-dark',
    value: '#333333',
    token: null,
    tailwindClass: null,
    category: 'pdf',
    label: 'PDF Dark Border',
    usedIn: ['pdf-report.tsx'],
    status: 'unresolved',
  },
  {
    id: 'pdf-border-light',
    value: '#eeeeee',
    token: null,
    tailwindClass: null,
    category: 'pdf',
    label: 'PDF Light Border',
    usedIn: ['pdf-report.tsx'],
    status: 'unresolved',
  },

  // ─── Brand ─────────────────────────────────────────────────────────────
  {
    id: 'brand-google-blue',
    value: '#4285F4',
    token: null,
    tailwindClass: null,
    category: 'brand',
    label: 'Google Blue',
    usedIn: ['LoginPage.tsx'],
    status: 'unresolved',
  },
  {
    id: 'brand-google-green',
    value: '#34A853',
    token: null,
    tailwindClass: null,
    category: 'brand',
    label: 'Google Green',
    usedIn: ['LoginPage.tsx'],
    status: 'unresolved',
  },
  {
    id: 'brand-google-amber',
    value: '#FBBC05',
    token: null,
    tailwindClass: null,
    category: 'brand',
    label: 'Google Amber',
    usedIn: ['LoginPage.tsx'],
    status: 'unresolved',
  },
  {
    id: 'brand-google-red',
    value: '#EA4335',
    token: null,
    tailwindClass: null,
    category: 'brand',
    label: 'Google Red',
    usedIn: ['LoginPage.tsx'],
    status: 'unresolved',
  },

  // ─── Misc unresolved ──────────────────────────────────────────────────
  {
    id: 'step-indicator',
    value: '#c5b99b',
    token: null,
    tailwindClass: null,
    category: 'form',
    label: 'Step Indicator',
    usedIn: ['ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'badge-new',
    value: '#f989e4',
    token: null,
    tailwindClass: null,
    category: 'form',
    label: 'New Badge (Pink)',
    usedIn: ['ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'upload-area-bg',
    value: '#ede8df',
    token: null,
    tailwindClass: null,
    category: 'form',
    label: 'Upload Area BG',
    usedIn: ['ImportWizard.tsx'],
    status: 'unresolved',
  },
  {
    id: 'gradient-start',
    value: '#fdf5ed',
    token: null,
    tailwindClass: null,
    category: 'core',
    label: 'Gradient Start',
    usedIn: ['index.css'],
    status: 'unresolved',
  },
  {
    id: 'gradient-end',
    value: '#d6cec6',
    token: null,
    tailwindClass: null,
    category: 'core',
    label: 'Gradient End',
    usedIn: ['index.css'],
    status: 'unresolved',
  },
  {
    id: 'body-bg',
    value: '#F0EAE4',
    token: null,
    tailwindClass: null,
    category: 'core',
    label: 'Body Background',
    usedIn: ['index.css'],
    status: 'unresolved',
  },
]
